"""Add client ID to revocation URLs

Revision ID: da70e75bc1a4
Revises: a73e0b144fd3
Create Date: 2017-04-09 22:38:51.860629

"""

# revision identifiers, used by Alembic.
revision = 'da70e75bc1a4'
down_revision = 'a73e0b144fd3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revocationurl', sa.Column('client_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'revocationurl', 'oauthclient', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'revocationurl', type_='foreignkey')
    op.drop_column('revocationurl', 'client_id')
    # ### end Alembic commands ###
