"""Add preauthorized to oauth clients

Revision ID: e3dc9b1bcf42
Revises: None
Create Date: 2017-04-06 07:10:27.410569

"""

# revision identifiers, used by Alembic.
revision = 'e3dc9b1bcf42'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauthclient', sa.Column('preauthorized', sa.Boolean(),
        nullable=False, server_default='f'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauthclient', 'preauthorized')
    # ### end Alembic commands ###
