"""Add OAuth types

Revision ID: 008e8eb42594
Revises: 56eed6c40399
Create Date: 2016-10-22 12:43:39.803841

"""

# revision identifiers, used by Alembic.
revision = '008e8eb42594'
down_revision = '56eed6c40399'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
