"""Remove audit log enabled

Revision ID: 21419bd9db4d
Revises: 008e8eb42594
Create Date: 2016-10-24 07:07:03.358049

"""

# revision identifiers, used by Alembic.
revision = '21419bd9db4d'
down_revision = '008e8eb42594'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'enable_audit_log')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('enable_audit_log', sa.BOOLEAN(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
