"""Add account PGP key

Revision ID: 56eed6c40399
Revises: None
Create Date: 2016-10-22 10:29:55.718985

"""

# revision identifiers, used by Alembic.
revision = '56eed6c40399'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pgp_key_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'pgpkey', ['pgp_key_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'pgp_key_id')
    ### end Alembic commands ###
