"""Add oauth client name column

Revision ID: a1ecfb20dcb3
Revises: fb612b171ab2
Create Date: 2016-10-25 07:49:11.930650

"""

# revision identifiers, used by Alembic.
revision = 'a1ecfb20dcb3'
down_revision = 'fb612b171ab2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauthclient', sa.Column('client_name', sa.Unicode(length=256), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauthclient', 'client_name')
    ### end Alembic commands ###
