"""Increase size of client secret hash column

Revision ID: fb612b171ab2
Revises: 21419bd9db4d
Create Date: 2016-10-25 07:42:53.117804

"""

# revision identifiers, used by Alembic.
revision = 'fb612b171ab2'
down_revision = '21419bd9db4d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    op.alter_column('oauthclient', 'client_secret_hash', type_=sa.String(128))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    op.alter_column('oauthclient', 'client_secret_hash', type_=sa.String(32))
